language: julia
julia: [1.0, 1.1, nightly]
matrix: {allow_failures: [{julia: nightly}]}
notifications: {email: false}
jobs:
  include:
    - stage: Documentation
      julia: 1.1
      script: julia --project=docs -e '
          using Pkg;
          Pkg.develop(PackageSpec(; path=pwd()));
          Pkg.instantiate();
          include(joinpath("docs", "make.jl"));'
      after_success: skip
